spring:
  profiles:
    active: local
  pid:
    file: dobi-api.pid

server:
  port: 5000

kakao:
  url:
    auth: https://kauth.kakao.com/
    api: https://kapi.kakao.com/


jwt:
  secret:
  expiration: 14800
  header: Authorization